In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
trout = pd.read_csv('../data/WestBrookTroutDataWhatleyMA.csv')

/var/folders/9k/_6hsswr52z55gh1n7b83gb2m0000gn/T/ipykernel_29699/2967566274.py:1: DtypeWarning: Columns (0: dateEmigrated, 1: sex) have mixed types. Specify dtype option on import or set low_memory=False.
  trout = pd.read_csv('../data/WestBrookTroutDataWhatleyMA.csv')

In [4]:
trout.head()

,Unnamed: 0,tag,cohort,detectionDate,sampleName,sampleNumber,river,section,area,observedLength,survey,observedWeight,species,dateEmigrated,sex,enc,ageInSamples,sampleIndex,tagIndex,year,season,proportionSampled,lagDetectionDate,meanTemperature,meanFlow,knownZ,sectionOriginal,riverOrdered,inside,yday,lagSection,distMoved,lagObservedWeight,lagObservedLength,grWeight,grLength,minSample,maxSample,minYear,moveDir,sampleInterval,drainage,quarter_length,river_meter,confluence_river_meter,riverMeter,countP,isYOY
0,1,00088cbed0,2012,3/25/2013 0:00,84.0,73,wb obear,7,trib,62.0,shock,1.9,bkt,NaN,NaN,1,3,63,1,2013,1,1.0,6/6/2013 0:00,8.671025,0.385292,1.0,7,wb obear,True,84,7.0,0.0,NaN,NaN,NaN,NaN,73,85,1997,0.0,73.000000,west,5.0,5251.7,5113.7,5251.7,NaN,1
1,2,00088cbed0,2012,6/6/2013 0:00,85.0,74,wb obear,7,trib,NaN,NaN,NaN,bkt,NaN,NaN,0,4,64,1,2013,2,NaN,9/23/2013 0:00,16.385399,0.291689,NaN,7,wb obear,True,157,7.0,0.0,NaN,NaN,NaN,NaN,73,85,1997,0.0,109.000000,west,5.0,5251.7,5113.7,NaN,NaN,2
2,3,00088cbed0,2012,9/23/2013 0:00,86.0,75,wb obear,7,trib,NaN,NaN,NaN,bkt,NaN,NaN,0,5,65,1,2013,3,NaN,11/19/2013 0:00,9.141904,0.008927,NaN,7,wb obear,True,266,7.0,0.0,NaN,NaN,NaN,NaN,73,85,1997,0.0,57.041667,west,5.0,5251.7,5113.7,NaN,NaN,2
3,4,00088cbed0,2012,11/19/2013 0:00,87.0,76,wb obear,7,trib,NaN,NaN,NaN,bkt,NaN,NaN,0,6,66,1,2013,4,NaN,4/4/2014 0:00,0.930404,0.313188,NaN,7,wb obear,True,323,7.0,0.0,NaN,NaN,NaN,NaN,73,85,1997,0.0,135.958333,west,5.0,5251.7,5113.7,NaN,NaN,2
4,5,00088cbed0,2012,4/4/2014 0:00,88.0,77,wb obear,7,trib,NaN,NaN,NaN,bkt,NaN,NaN,0,7,67,1,2014,1,NaN,6/12/2014 0:00,10.504816,0.583629,NaN,7,wb obear,True,94,7.0,0.0,NaN,NaN,NaN,NaN,73,85,1997,0.0,69.000000,west,5.0,5251.7,5113.7,NaN,NaN,2

In [5]:
trout.shape

(451220, 48)

In [6]:
trout.info()

<class 'pandas.DataFrame'>
RangeIndex: 451220 entries, 0 to 451219
Data columns (total 48 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Unnamed: 0              451220 non-null  int64
 1   tag                     451220 non-null  str
 2   cohort                  451220 non-null  int64
 3   detectionDate           451220 non-null  str
 4   sampleName              451220 non-null  float64
 5   sampleNumber            451220 non-null  int64
 6   river                   451220 non-null  str
 7   section                 451220 non-null  int64
 8   area                    451220 non-null  str
 9   observedLength          63073 non-null   float64
 10  survey                  63113 non-null   str
 11  observedWeight          62989 non-null   float64
 12  species                 451220 non-null  str
 13  dateEmigrated           12558 non-null   str
 14  sex                     32532 non-null   str
 15  enc                     451220 non-null  int64
 16  ageInSamples            451220 non-null  int64
 17  sampleIndex             451220 non-null  int64
 18  tagIndex                451220 non-null  int64
 19  year                    451220 non-null  int64
 20  season                  451220 non-null  int64
 21  proportionSampled       63113 non-null   float64
 22  lagDetectionDate        422337 non-null  str
 23  meanTemperature         422337 non-null  float64
 24  meanFlow                422337 non-null  float64
 25  knownZ                  84708 non-null   float64
 26  sectionOriginal         451220 non-null  int64
 27  riverOrdered            451220 non-null  str
 28  inside                  442174 non-null  object
 29  yday                    451220 non-null  int64
 30  lagSection              422337 non-null  float64
 31  distMoved               422337 non-null  float64
 32  lagObservedWeight       34159 non-null   float64
 33  lagObservedLength       34197 non-null   float64
 34  grWeight                23352 non-null   float64
 35  grLength                23415 non-null   float64
 36  minSample               451220 non-null  int64
 37  maxSample               451220 non-null  int64
 38  minYear                 451220 non-null  int64
 39  moveDir                 422337 non-null  float64
 40  sampleInterval          422337 non-null  float64
 41  drainage                450282 non-null  str
 42  quarter_length          450282 non-null  float64
 43  river_meter             450282 non-null  float64
 44  confluence_river_meter  450282 non-null  float64
 45  riverMeter              62977 non-null   float64
 46  countP                  0 non-null       float64
 47  isYOY                   451220 non-null  int64
dtypes: float64(20), int64(16), object(1), str(11)
memory usage: 165.2+ MB

In [7]:
trout['Unnamed: 0'].value_counts().head(20)

Unnamed: 0
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
Name: count, dtype: int64

In [8]:
trout['tag'].value_counts().head(20)

tag
4.14E+33      57
00088cf4c6    21
00088cf629    21
00088cf69e    21
00088cf712    21
00088cf77f    21
00088d08be    21
00088d08ce    21
00088d08e6    21
00088d0a45    21
00088d0be6    21
00088d1988    21
00088d1998    21
00088d1ae4    21
00088d1b4a    21
00088d1bfa    21
00088d2152    21
00088d21df    21
00088d2200    21
00088d230f    21
Name: count, dtype: int64

In [9]:
trout['cohort'].value_counts()

cohort
2004    50254
2009    48071
2003    43845
2001    39440
2012    39395
2000    35661
1998    29854
2002    25607
1999    23544
2006    18220
2008    16418
2010    16271
2005    15102
1997    11615
2007    11574
2013     9649
2011     8166
2014     7979
2015      555
Name: count, dtype: int64

From metadata: cohort = year born

In [10]:
trout['survey'].value_counts()

survey
shock    63113
Name: count, dtype: int64

In [11]:
trout['observedWeight'].describe()

count    62989.000000
mean        16.253463
std         45.394629
min      -9999.900000
25%          4.200000
50%          9.300000
75%         20.000000
max        473.600000
Name: observedWeight, dtype: float64

In [12]:
# How many values are negative?

(trout['observedWeight'] < 0).sum()

np.int64(1)

In [14]:
# Replacing negative weights with nulls (although there is only one)

trout.loc[trout['observedWeight'] < 0, 'observedWeight'] = float('nan')

In [15]:
trout['observedWeight'].describe()

count    62988.000000
mean        16.412480
std         21.631397
min          1.100000
25%          4.200000
50%          9.300000
75%         20.000000
max        473.600000
Name: observedWeight, dtype: float64

In [16]:
trout.groupby('species')['observedWeight'].describe()

           count       mean        std  min  25%   50%   75%    max
species
ats      19375.0  12.137894  10.455734  1.1  4.1   8.5  17.2  110.6
bkt      29163.0  14.365833  15.953587  1.3  4.0   8.5  18.9  269.2
bnt      14450.0  26.274519  35.345199  1.7  4.9  12.9  32.7  473.6

Observations:
Brook trout are the most numerous.
The smallest fish is a salmon.
The largest fish is a brown trout--by far.
Brown trout have the largest average weight.
Brown trout have the largest standard deviation.